// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmevbR0G9U1858bMtCy8K_Bm7XcXCBqaI',
    appId: '1:731808882757:web:5135e230fe7e482add832c',
    messagingSenderId: '731808882757',
    projectId: 'sportfolio-23e77',
    authDomain: 'sportfolio-23e77.firebaseapp.com',
    storageBucket: 'sportfolio-23e77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQ3ca1gbw1JO32eBfkWFlrzmGd5_9BG8',
    appId: '1:731808882757:android:d7cbadffcef1336bdd832c',
    messagingSenderId: '731808882757',
    projectId: 'sportfolio-23e77',
    storageBucket: 'sportfolio-23e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBkXWMuErk-5MyTwYMELsCD-Sx0Dqenk',
    appId: '1:731808882757:ios:f1490167cabb296bdd832c',
    messagingSenderId: '731808882757',
    projectId: 'sportfolio-23e77',
    storageBucket: 'sportfolio-23e77.firebasestorage.app',
    iosBundleId: 'com.example.sportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJBkXWMuErk-5MyTwYMELsCD-Sx0Dqenk',
    appId: '1:731808882757:ios:f1490167cabb296bdd832c',
    messagingSenderId: '731808882757',
    projectId: 'sportfolio-23e77',
    storageBucket: 'sportfolio-23e77.firebasestorage.app',
    iosBundleId: 'com.example.sportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmevbR0G9U1858bMtCy8K_Bm7XcXCBqaI',
    appId: '1:731808882757:web:a79b61f1193811a6dd832c',
    messagingSenderId: '731808882757',
    projectId: 'sportfolio-23e77',
    authDomain: 'sportfolio-23e77.firebaseapp.com',
    storageBucket: 'sportfolio-23e77.firebasestorage.app',
  );
}
